apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
        - name: react-app
          image:  ghcr.io/demo-Organization-m/python-application:latest
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
