apiVersion: v1
kind: Service
metadata:
  name: python-application-service
spec:
  type: LoadBalancer
  selector:
    app: python-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
